name: OSACUBS
favicon: null
layout_spectrum: 0.75901
typography_spectrum: 0.31584
title: OSACUB AGENCY
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5
  lightness: 0.5162423443980515
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
